[package]
name = "node_aff10_weight"
version = "0.1.0"
edition = "2023_10"

[dependencies]
orion = { git = "https://github.com/Vid201/orion.git", branch = "chore/update_deps" } 
[lib]
sierra-text = true